name: colormix
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  vector_math: '>=2.0.8'

dev_dependencies:
  pedantic: ^1.0.0
  build_runner: '>=1.3.0 <2.0.0'
  build_test: ^0.10.2
  build_web_compilers: '>=2.6.1 <3.0.0'
